sudo: true

language: bash

services:
  - docker

env:
  global:
    - DOCKERHUB="tzinm/remove-finished"

jobs:
  include:
    - stage: BuildImage
      if: (NOT (type IN (pull_request)))
      script:
        # Build image
        - docker build --no-cache -t ${DOCKERHUB}:${TRAVIS_COMMIT} .
        - docker tag ${DOCKERHUB}:${TRAVIS_COMMIT} ${DOCKERHUB}:latest
        # Login to DockerHub
        - docker login -u $DOCKERUSER --password-stdin <(echo $DOCKERPASS)
        # Push all of the tags
        - docker push ${DOCKERHUB}:${TRAVIS_COMMIT}
        - docker push ${DOCKERHUB}:latest
